# Generated by Django 3.2.8 on 2022-05-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_studentname_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentname',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
