# Generated by Django 3.2.8 on 2022-05-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_studentname_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentname',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
