# Generated by Django 3.2.8 on 2022-05-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_studentname_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentname',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
