# Generated by Django 3.2.8 on 2022-05-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_studentname_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentAttend',
        ),
        migrations.DeleteModel(
            name='studentinfo',
        ),
    ]
