# Generated by Django 3.2.8 on 2022-05-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20220516_0018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminsInfo',
        ),
    ]
